name: Dependency Check

on:
  push:
    branches:
      - main

jobs:
  dependency_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GHC
        run: stack setup

      - name: Run Dependency Check
        id: dependency_check
        run: |
          chmod +x dependency_check.sh
          output=$(./dependency_check.sh MyPackage.cabal)
          echo "::set-output name=dependency_report::$output"
