name: Dependency Check

on:
  push:
    branches:
      - main

jobs:
  dependency_check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Cabal
        uses: haskell/actions/setup-cabal@v1

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GHC
        uses: haskell/actions/setup@v1

      - name: Build and Test
        run: |
          chmod +x dependency_check.sh
          ./dependency_check.sh MyPackage.cabal
